### ISSUE TITLE
Class __init__ docstrings don't go into docs

### ISSUE THREAD

**Issue by svank** [punch-mission/regularizepsf#189]
I just saw this problem with my own docs, and I was checking here to see if you had a solution, since I copied your docs setup. When a class has a docstring and its `__init__` also has a docstring, only the class docstring goes into the docs, and the `__init__` docstring gets eaten. See, e.g., [`FunctionalCorrector`](https://punch-mission.github.io/regularizepsf/autoapi/regularizepsf/corrector/index.html#regularizepsf.corrector.FunctionalCorrector), whose [`__init__` docstring](https://github.com/punch-mission/regularizepsf/blob/7f287fce0119a914e76cd45522a650174fafdec6/regularizepsf/corrector.py#L92) goes nowhere. This means the input arguments to the class constructor don't get documented.

One solution is to add `autoapi_python_class_content = 'both'` to `docs/source/conf.py`, to concatenate the `__init__` docstring to the class docstring

**Comment by jmbhughes** [comment]
Thanks. I'll look into this.
