### ISSUE TITLE
Add scheduled workflow runs

### ISSUE THREAD

**Issue by WilliamJamieson** [punch-mission/regularizepsf#35]
As part of glancing through regularizePSF for your Affiliated package request in astropy/astropy.github.com#528, I noticed that your CI was only being run on pull requests. It is wonderful that you have GitHub actions CI setup!

I do have one suggestion for your CI, you should run it on a cron see: [astropy](https://github.com/astropy/astropy/blob/edf7493ec141a9072b5ce3e33071dff66e58bf49/.github/workflows/ci_cron_weekly.yml#L4-L6), though you don't have to run it as regularly as what I linked to. This is not formally part of the review or its requirements; however, it maybe useful to have it run automatically as this package is probably not having a constant stream of PRs being made. Doing so will give you some warning of one of your dependencies causing you issues.

**Comment by jmbhughes** [comment]
Great suggestion! I'll try to do this soon.
