### ISSUE TITLE
Neighborhood box size. Question

### ISSUE THREAD

**Issue by sumanchapai** [punch-mission/regularizepsf#39]
https://github.com/punch-mission/regularizepsf/blob/02e770a3dd8db08e74ef2f98ea719167619d462e/docs/quickstart.md?plain=1#L46C1-L47C1

I was wondering why the neighborhood box size is `256x255` and not `256x256`

**Comment by jmbhughes** [comment]
Excellent catch! That's a typo. It should be 256 on both sides. You're welcome to open a pull request to fix it or I can take care of it later. Thank you for the question!
