### ISSUE TITLE
Single image vs multiple while making model. Question

### ISSUE THREAD

**Issue by sumanchapai** [punch-mission/regularizepsf#41]
The code gives option of using multiple images to make a model. If using multiple images, do they all have to be aligned so that the star patterns are in same pixel positions? If so, does the code take care of removing zeros when taking the median because some of our images after alignment end up with zeros at the edges when the field (this is dynamic from image to image night to night, depends on how different was the telescope's position from reference image.

**Comment by sumanchapai** [comment]
Also wondering whether we should use the same model for next night or make new model... I guess what I am also asking is whether the comma effect is associated with a pixel or a star... if it was associated with a pixel then one could just generate a model once and use it always until change of equipment?

**Comment by jmbhughes** [comment]
When using multiple images, the stars don't need to be in the same position. In fact it could be better if they're not because that allows you to measure the PSF in more places and potentially use a finer grid. 

The coma effect is a consequence of the telescope/imager optics. It may change over time if something alters your setup, but for the most part you should be able to generate the model once and always use it. 

Does that answer your question? Could we make this clearer in the documentation somehow?

**Comment by jmbhughes** [comment]
Also I'd love to hear more about how you plan to use `regularizePSF`.

**Comment by sumanchapai** [comment]
Thank you. You answered my question. I noticed in the docs that it says "you need a PSF model for the system that collected the image" so on a second read it's clear. In our specific case, we wanted to make sure whether we needed aligned images or not; maybe saying it explicitly in the docs could be helpful. 

We've over 20 years of data on the M23 cluster taken from Luther College, Decorah Iowa. We have had to change our camera and telescope during this period and noticed that our earlier telescope had a coma that we want to correct for. We're hoping to somewhat clear the discontinuity in our light curves after applying correction.

**Comment by jmbhughes** [comment]
That's super interesting. I'm going to close this issue. But if you need any help, please don't hesitate to ask. If you get some results, I'd be excited to see them and potentially, with your permission, use them as an example of the code working.
