### ISSUE TITLE
Windows installation issue

### ISSUE THREAD

**Issue by sumanchapai** [punch-mission/regularizepsf#48]
I am running into the following issue trying to install `regularizepsf` on windows. Is this a known issue?

![image](https://github.com/punch-mission/regularizepsf/assets/26862106/596b5c17-25ff-4b06-b04b-d2016448f06d)

It says something like requiring "Microsoft Visual C++ 14.0 or greater". I just wanted to make sure that it's the issue and not something else.

**Comment by jmbhughes** [comment]
I think this is to be expected. Some of the code is written in Cython for speed, which requires compilation. You just need to follow the instructions listed there and it should be resolved. Let me know if it results in any issues.

**Comment by sumanchapai** [comment]
That was it. It just needed C++ 14.0 or greater. Worked after that. Thanks
