### ISSUE TITLE
HDF5 path specification issue

### ISSUE THREAD

**Issue by lowderchris** [punch-mission/regularizepsf#8]
Ran across an issue trying to setup this repository locally on an ARM Mac. Details below:

- Installed HDF5 library using homebrew - note that this defaults to /opt/homebrew/ on ARM Macs rather than /usr/local/
- Cloned regularizepsf repository locally from GitHub
- On setting up the virtualenv, an error was triggered when PyCharm was attempting to install the requirement deepdish:

`      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.`

On setting the environmental variable HDR5_DIR to my .zprofile startup file to point towards /opt/homebrew/opt/hdf5, this at first did not seem to work within PyCharm's virtualenv setup. After a reboot of my machine, this *did*, however, seem to work.

**Comment by jmbhughes** [comment]
Thanks. I'll look into this. Reboots are magical.

**Comment by jmbhughes** [comment]
I haven't been able to recreate this, and it sounds like it resolved itself for you. I'm going to close it for now. If we see it again, we can reopen.
